sudo: required
services:
  - docker

before_install:
  - docker build -t jpaps/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jpaps/react-test npm test

after_success:
  - docker build -t jpaps/multi-client ./client
  - docker build -t jpaps/multi-nginx ./nginx
  - docker build -t jpaps/multi-server ./server
  - docker build -t jpaps/multi-worker ./worker
  #login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push jpaps/multi-client
  - docker push jpaps/multi-nginx
  - docker push jpaps/multi-server
  - docker push jpaps/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-central-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-eu-central-1-644726204831'
  bucket_path: 'docker-multi'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY